const winnerList = [
  { name: "Shariz", image_path: "/winners/shariz-2.jpg" },
  { name: "Munni", image_path: "/winners/munni-2.jpg" },
  { name: "Angie", image_path: "/winners/angie-1.jpg" },
  { name: "Imma", image_path: "/winners/imma-2.jpg" },
  { name: "Munni", image_path: "/winners/munni-1.jpg" },
  { name: "Imma", image_path: "/winners/imma-1.jpg" },
  { name: "Hamid", image_path: "/winners/hamid-1.jpg" },
  { name: "Ice", image_path: "/winners/ice-1.jpg" },
  { name: "Yameen", image_path: "/winners/yameen-1.jpg" },
  { name: "Liva", image_path: "/winners/liva-1.jpg" },
  { name: "Modo", image_path: "/winners/modo-2.jpg" },
  { name: "Raya", image_path: "/winners/raya-2.jpg" },
  { name: "Abu", image_path: "/winners/abu-1.jpg" },
  { name: "Layana", image_path: "/winners/layana-1.jpg" },
  { name: "Shariz", image_path: "/winners/shariz-1.jpg" },
  { name: "Modo", image_path: "/winners/modo-1.jpg" },
  { name: "Raya", image_path: "/winners/raya-1.jpg" },
  { name: "Azhadh", image_path: "/winners/azhadh-1.jpg" },
  { name: "Mohd", image_path: "/winners/mohd-1.jpg" },
  { name: "Shamikh", image_path: "/winners/shamikh-1.jpg" },
  { name: "Sara", image_path: "/winners/sara-1.jpg" },
];

export { winnerList };